# Generated by Django 4.0.5 on 2022-06-23 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='runner_type',
            field=models.CharField(max_length=100),
        ),
    ]
