# Generated by Django 4.0.5 on 2022-06-23 08:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_runner_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='runner_type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None),
        ),
    ]
