# Generated by Django 4.0.5 on 2022-06-26 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_runnerlevel_profile_runner_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunnerTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='RunnerType',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='runner_type',
        ),
        migrations.AddField(
            model_name='profile',
            name='runner_tag',
            field=models.ManyToManyField(to='users.runnertag'),
        ),
    ]
