# Generated by Django 4.0.5 on 2022-06-26 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_runnertag_delete_runnertype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
