# Generated by Django 4.0.5 on 2022-06-23 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_runner_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='runner_type',
            field=models.CharField(choices=[('AVID', 'Avid'), ('COMPETITIVE', 'Competitive'), ('FAST', 'Fast')], max_length=200),
        ),
    ]
