# Generated by Django 4.0.5 on 2022-06-23 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_age'),
        ('users', '0005_alter_profile_runner_type'),
    ]

    operations = [
    ]
