# Generated by Django 4.0.5 on 2022-06-28 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_date_of_birth_profile_estimated10k_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(max_length=8),
        ),
    ]
