# Generated by Django 4.0.5 on 2022-07-04 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_alter_event_creator_remove_event_participants_and_more'),
        ('users', '0008_remove_profile_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='participation',
            field=models.ManyToManyField(related_name='participation', to='events.event'),
        ),
    ]
