# Generated by Django 4.0.5 on 2022-07-05 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_profile_participation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='participation',
        ),
    ]
