# Generated by Django 4.0.5 on 2022-06-23 08:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_running_duration_event_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 6, 23, 17, 38, 5, 649566)),
        ),
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.TimeField(default=datetime.datetime(2022, 6, 23, 17, 38, 5, 649566)),
        ),
    ]
