# Generated by Django 4.0.5 on 2022-06-27 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_description_event_image_alter_event_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='lat',
            field=models.DecimalField(decimal_places=16, default='0.00', max_digits=19),
        ),
        migrations.AddField(
            model_name='event',
            name='long',
            field=models.DecimalField(decimal_places=16, default='0.00', max_digits=19),
        ),
    ]
