# Generated by Django 4.0.5 on 2022-06-23 12:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_description_event_image_alter_event_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 6, 23, 21, 56, 42, 925775)),
        ),
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.TimeField(default=datetime.datetime(2022, 6, 23, 21, 56, 42, 925775)),
        ),
    ]
