# Generated by Django 4.0.5 on 2022-06-24 03:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_remove_event_date_remove_event_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 24, 3, 26, 13, 439702, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 24, 3, 26, 13, 440009, tzinfo=utc)),
        ),
    ]
