# Generated by Django 4.0.5 on 2022-07-02 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_event_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='profile_image',
        ),
    ]
