# Generated by Django 4.0.5 on 2022-07-05 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_alter_event_creator_remove_event_participants_and_more'),
        ('events', '0015_remove_event_profile'),
    ]

    operations = [
    ]
