# Generated by Django 4.0.5 on 2022-07-07 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointsofinterest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointofinterest',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pointofinterest',
            name='jp_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
