# Generated by Django 4.0.5 on 2022-06-22 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward_name', models.CharField(choices=[('ADACHI-KU', 'Adachi-Ku'), ('ARAKAWA-KU', 'Arakawa-Ku'), ('BUNKYO-KU', 'Bunkyo-Ku'), ('CHIYODA-KU', 'Chiyoda-Ku'), ('CHUO-KU', 'Chuo-Ku'), ('EDOGAWA-KU', 'Edogawa-Ku'), ('ITABASHI-KU', 'Itabashi-Ku'), ('KATSUSHIKA-KU', 'Katsushika-Ku'), ('KITA-KU', 'Kita-Ku'), ('KOTO-KU', 'Koto-Ku'), ('MINATO-KU', 'Minato-Ku'), ('MEGURO-KU', 'Meguro-Ku'), ('NAKANO-KU', 'Nakano-Ku'), ('NERIMA-KU', 'Nerima-Ku'), ('OTA-KU', 'Ota-Ku'), ('SETAGAYA-KU', 'Setagaya-Ku'), ('SHIBUYA-KU', 'Shibuya-Ku'), ('SHINAGAWA-KU', 'Shinagawa-Ku'), ('SHINJUKU-KU', 'Shinjuku-Ku'), ('SUGINAMI-KU', 'Suginami-Ku'), ('SUMIDA-KU', 'Sumida-Ku'), ('TAITO-KU', 'Taito-Ku'), ('TOSHIMA-KU', 'Toshima-Ku')], default='ADACHI-KU', max_length=50)),
            ],
        ),
    ]
