# Generated by Django 4.0.5 on 2022-06-22 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward_name', models.CharField(choices=[('ADACHI', 'Adachi'), ('ARAKAWA', 'Arakawa'), ('BUNKYO', 'Bunkyo'), ('CHIYODA', 'Chiyoda'), ('CHUO', 'Chuo'), ('EDOGAWA', 'Edogawa'), ('ITABASHI', 'Itabashi'), ('KATSUSHIKA', 'Katsushika'), ('KITA', 'Kita'), ('KOTO', 'Koto'), ('MINATO', 'Minato'), ('MEGURO', 'Meguro'), ('NAKANO', 'Nakano'), ('NERIMA', 'Nerima'), ('OTA', 'Ota'), ('SETAGAYA', 'Setagaya'), ('SHIBUYA', 'Shibuya'), ('SHINAGAWA', 'Shinagawa'), ('SHINJUKU', 'Shinjuku'), ('SUGINAMI', 'Suginami'), ('SUMIDA', 'Sumida'), ('TAITO', 'Taito'), ('TOSHIMA', 'Toshima')], default='ADACHI', max_length=50)),
            ],
        ),
    ]
