# Generated by Django 4.0.5 on 2022-06-22 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wards', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wards',
            new_name='Ward',
        ),
    ]
