# Generated by Django 4.0.5 on 2022-06-22 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location_types', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long', models.DecimalField(decimal_places=16, max_digits=19)),
                ('lat', models.DecimalField(decimal_places=16, max_digits=18)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location_types.locationtype')),
            ],
        ),
    ]
